jQuery(function($) {ServicesModuleInitialize();});function ServicesModuleInitialize() {$(document).on('s123.page.ready', function( event ) {var $section = $('section.s123-module-services');$section.each(function( index ) {var $sectionThis = $(this);var categories = new ModuleLayoutCategories({$items :  $sectionThis.find('.services-category'),$categoriesContainer : $sectionThis.find('.categories-panel'),$filterButton : $sectionThis.find('.items-responsive-filter'),$categories : $sectionThis.find('.items-categories-container li')});if ( $sectionThis.hasClass('layout-10') ) {$sectionThis.find('.service-item-description').each(function() {const $paragraph = $(this);const element = $paragraph.get(0);if (element.scrollHeight > element.clientHeight) {$paragraph.addClass('show-more');$paragraph.attr('data-rel', 'tooltip');$paragraph.off('click.openMore').on('click.openMore', function() {var $this = $(this);if ( $this.hasClass('show-more-disabled') ) return;bootbox.alert({title: $this.data('title'),message: $this.html(),backdrop: true});});}});}
if ( $sectionThis.hasClass('layout-13') ) {$sectionThis.find('.services-category').each(function() {$sectionThis.find('.service-item').removeClass('active');$sectionThis.find('.service-image').removeClass('active');$sectionThis.find('.service-info').addClass('service-more-info-hidden');var $firstItem = $(this).find('.service-item').first();$firstItem.addClass('active');var imgKey = $firstItem.data('img-key');if (imgKey !== undefined) {$sectionThis.find('.service-image[data-img-key="' + imgKey + '"]').addClass('active');var $firstInfo = $sectionThis.find('.service-info[data-img-key="' + imgKey + '"]');if ($firstInfo.length > 0) {$firstInfo.removeClass('service-more-info-hidden');}}});$sectionThis.find('.service-items .service-item').on('click mouseenter',function() {let $this = $(this);if ( $this.hasClass('active') ) return;let imgKey = $this.data('img-key');$sectionThis.find('.service-item').removeClass('active');$sectionThis.find('.service-image.active').stop().fadeOut(500).removeClass('active');$sectionThis.find('.service-info').addClass('service-more-info-hidden');$sectionThis.find('.service-item[data-img-key="' + imgKey + '"]').addClass('active');var $newImage = $sectionThis.find('.service-image[data-img-key="' + imgKey + '"]');$newImage.addClass('active').stop().fadeIn(500);var $targetInfo = $sectionThis.find('.service-info[data-img-key="' + imgKey + '"]');if ($targetInfo.length > 0) {$targetInfo.removeClass('service-more-info-hidden');}});$sectionThis.off('module_layout_categories.shown').on('module_layout_categories.shown', function( event, catID ) {var $category = $(this).find('.services-category[data-categories-filter="'+catID+'"]');$sectionThis.find('.service-item').removeClass('active');$sectionThis.find('.service-image.active').fadeOut(500).removeClass('active');$sectionThis.find('.service-image').removeClass('active');$sectionThis.find('.service-info').addClass('service-more-info-hidden');var imgKey = $category.find('.service-item:first-child').data('img-key');if (imgKey !== undefined) {$sectionThis.find(`.service-item[data-img-key="${imgKey}"]`).addClass('active');$sectionThis.find(`.service-image[data-img-key="${imgKey}"]`).addClass('active').fadeIn(500);var $targetInfo = $sectionThis.find(`.service-info[data-img-key="${imgKey}"]`);if ($targetInfo.length > 0) {$targetInfo.removeClass('service-more-info-hidden');}}});}
$modulesMobileCarouselViewOBJ = new ModulesMobileCarouselView({$section : $sectionThis});if ( $sectionThis.find('.mapPopupActivator').length > 0 ) {$sectionThis.find('.mapPopupActivator').each(function() {var $mapLink = $(this);var location = $mapLink.data('location');$mapLink.off('click.mapPopup').on('click.mapPopup', function(e) {e.preventDefault();buildPopup('popupServiceMap','','', $GLOBALS["maps-display-domain"] + '/include/globalMapDisplay.php?cad=1&q=' + encodeURIComponent(location) + '&fl=1&l=' + encodeURIComponent(languageCode) + '&ilfc=' + encodeURIComponent(longFreeCustomer), true, false, true, '', '');});});}
initPseudoLinks($sectionThis);initAttributePopovers($sectionThis);});});function initPseudoLinks($container) {var $pseudoLinks = $container.find('[data-link-element="true"][data-href]');if ( $pseudoLinks.length === 0 ) return;$pseudoLinks.off('mousedown.pseudoLink').on('mousedown.pseudoLink', function(e) {if (e.which === 2) {e.preventDefault();e.stopPropagation();var href = $(this).data('href');if (href) {window.open(href, '_blank');}}});$pseudoLinks.off('click.pseudoLink').on('click.pseudoLink', function(e) {e.preventDefault();e.stopPropagation();var $el = $(this);var href = $el.data('href');var target = $el.data('target');if ( !href ) return;var open_in_new_tab_boo = e.ctrlKey || e.metaKey || target === '_blank';if ( open_in_new_tab_boo ) {window.open(href, '_blank');} else {window.location.href = href;}});$pseudoLinks.off('auxclick.pseudoLink').on('auxclick.pseudoLink', function(e) {if (e.which === 2) {e.preventDefault();e.stopPropagation();}});}
function initAttributePopovers($container) {var $attrElements = $container.find('.service-extra-attr');if ( $attrElements.length === 0 ) return;$attrElements.each(function() {var $attrEl = $(this);var titleText = $attrEl.attr('title');if ( !titleText || titleText.trim() === '' ) return;$attrEl.popover({container: 'body',content: titleText,html: false,trigger: 'hover',placement: 'top',template: '<div class="popover service-attr-popover" role="tooltip"><div class="arrow"></div><div class="popover-content"></div></div>'});});}}
jQuery(function($) {TestimonialsModuleInitialize_Layout1_Layout8_Layout9();});function TestimonialsModuleInitialize_Layout1_Layout8_Layout9() {$(document).on('s123.page.ready', function( event ) {var $sections = $('.s123-module-testimonials.layout-1, .s123-module-testimonials.layout-8, .s123-module-testimonials.layout-9');$sections.each(function( index ) {var $s = $(this);var $carousel = $s.find('[data-ride="carousel"]');var layout_customize = $s.find('.layout-customize').length > 0 ? tryParseJSON($s.find('.layout-customize').val()) : '';var testimonialsInterval = 10000;if ( layout_customize != '' ) {testimonialsInterval = layout_customize.testimonialsInterval * 1000;}
$carousel.carousel({interval: isMobileDevice.any() ? false : testimonialsInterval});$carousel.find('.carousel-control.left').click(function() {$carousel.carousel('prev');});$carousel.find('.carousel-control.right').click(function() {$carousel.carousel('next');});$carousel.find('.carousel-indicators li').click(function(){$carousel.carousel($(this).data('slide-to'));});});});$( document ).on( "s123.page.load", function( event ) {setTestimonialsHeight();});if ( IsWizard() ) {$(document).on('wizard.preview.device.changed', function( event ) {setTestimonialsHeight();});}
function setTestimonialsHeight() {var $sections = $('.s123-module-testimonials.layout-1, .s123-module-testimonials.layout-8, .s123-module-testimonials.layout-9');$sections.each(function( index ) {var $s = $(this);var $carousel = $s.find('[data-ride="carousel"]');$carousel.find('.item, .testimonial-image').css({ minHeight: '' });if ( !IsIE11() ) {var selector = $s.hasClass('layout-8') && findBootstrapEnvironment() !== 'xs' ? '.testimonial-image' : '.item';$carousel.find(selector).css({minHeight: Math.max.apply(Math, $carousel.find('.item').map(function() { return $(this).outerHeight(); }))});}});}}
jQuery(function($) {TestimonialsModuleInitialize_Layouts();setTimeout(function() {var $globalSections = $('.global-layout-2');if ($globalSections.length > 0 && typeof window.GlobalLayout2 === 'undefined') {const script = document.createElement('script');script.src = '/versions/2/wizard/modules/globalLayouts/globalLayout-vertical-scroll/js/module.globalLayout-2.js';document.head.appendChild(script);}}, 500);});function TestimonialsModuleInitialize_Layouts() {$(document).on('s123.page.ready', function( event ) {var $sections = $('.s123-module-testimonials');$sections.each(function( index ) {var $s = $(this);var $categories = $s.find('.testimonials-category');var categories = new ModuleLayoutCategories({$items :  $s.find('.testimonials-category'),$categoriesContainer : $s.find('.categories-panel'),$filterButton : $s.find('.items-responsive-filter'),$categories : $s.find('.items-categories-container li')});if ($s.hasClass('layout-13')) {initializeTestimonialsLayout13($s);}
if ($s.hasClass('layout-14') && $s.hasClass('global-layout-2')) {if (typeof window.GlobalLayout2 === 'undefined') {const script = document.createElement('script');script.src = '/versions/2/wizard/modules/globalLayouts/globalLayout-vertical-scroll/js/module.globalLayout-2.js';script.onload = function() {if (typeof window.GlobalLayout2 !== 'undefined') {window.GlobalLayout2.initialize();}};document.head.appendChild(script);} else {if (typeof window.GlobalLayout2.initialize === 'function') {window.GlobalLayout2.initialize();}}}});});}
function initializeTestimonialsLayout13($section) {var $rows = $section.find('.testimonials-row[data-animate="true"]');if ($rows.length === 0) return;function adjustAnimationForScreenSize() {$rows.each(function() {var $row = $(this);var $grid = $row.find('.testimonials-grid');var baseDuration = parseFloat($row.attr('data-animation-duration')) || 30;var totalItems = parseInt($row.attr('data-total-items')) || 0;var originalItems = parseInt($row.attr('data-original-items')) || 0;if (totalItems === 0 || originalItems === 0) return;var screenWidth = $(window).width();var baseScreenWidth = 1920; // Desktop width used in PHP calculation
var itemWidth = screenWidth <= 767 ? 250 : 280; // Mobile vs Desktop
var screenRatio = baseScreenWidth / screenWidth;var adjustedDuration = baseDuration * Math.sqrt(screenRatio); // Use sqrt for gentler scaling
var itemsOnScreen = Math.ceil(screenWidth / itemWidth);var itemRatio = Math.min(originalItems / itemsOnScreen, 3); // Cap at 3x
if (itemRatio < 1.5) {adjustedDuration *= 1.2; // 20% slower for sparse layouts
}
adjustedDuration = Math.max(9, Math.min(adjustedDuration, 106));$grid.css('animation-duration', adjustedDuration + 's');});}
adjustAnimationForScreenSize();var resizeTimer;$(window).on('resize', function() {clearTimeout(resizeTimer);resizeTimer = setTimeout(function() {adjustAnimationForScreenSize();}, 250);});}
jQuery(function($) {TestimonialsModuleInitialize_Layout12();});function TestimonialsModuleInitialize_Layout12() {$(document).on('s123.page.ready', function( event ) {var $sections = $('.s123-module-testimonials.layout-12');$sections.each(function( index ) {var $s = $(this);var $categories = $s.find('.testimonials-category');var categories = new ModuleLayoutCategories({$items :  $s.find('.testimonials-category'),$categoriesContainer : $s.find('.categories-panel'),$filterButton : $s.find('.items-responsive-filter'),$categories : $s.find('.items-categories-container li')});var $carousel = $($s.find('.testimonials-continuous-slider').get(0));var slidesToShow = whatScreen.any() == 'mobile' ? 1 : 3;$(window).on('resize', function() {if (whatScreen.any() == 'mobile') {slidesToShow = 1;} else {slidesToShow = 3;}
$carousel.slick('destroy');testimonialsLayout12Slick($carousel,slidesToShow);});if ( !$carousel.hasClass('slick-initialized') ) {testimonialsLayout12Slick($carousel,slidesToShow);}
$s.on('module_layout_categories.show', function (event, category) {$carousel.slick('destroy');$carousel = $s.find('.testimonials-category[data-categories-filter="'+category+'"] .testimonials-continuous-slider');if ( !$carousel.hasClass('slick-initialized') ) {testimonialsLayout12Slick($carousel,slidesToShow);}});});});}
function testimonialsLayout12Slick( $carousel, slidesToShow ) {$carousel.slick({slidesToShow: slidesToShow,  // number of slides to show at once
slidesToScroll: 1,  // number of slides to scroll at once
autoplay: true,infinite: true,speed: 8000,  // speed of the transition, play with this value to achieve desired effect
autoplaySpeed: 0,  // no delay between auto-play transitions
cssEase: 'linear',  // this gives the linear movement between slides
arrows: false,  // optional: disable arrows
pauseOnHover: true,  // optional: prevent pause when hover
draggable: false,centerMode: false,rtl: $('html').attr('dir') == 'rtl' ? true : false,adaptiveHeight: true});}
jQuery(function($) {TestimonialsModuleInitialize_Layout16();});function TestimonialsModuleInitialize_Layout16() {$(document).on('s123.page.ready', function(event) {var $sections = $('.s123-module-testimonials.layout-16');$sections.each(function(index) {var $s = $(this);var $categories = $s.find('.testimonials-category');var layout_customize = $s.find('.layout-customize').length > 0 ? tryParseJSON($s.find('.layout-customize').val()) : '';var categories = new ModuleLayoutCategories({$items: $s.find('.testimonials-category'),$categoriesContainer: $s.find('.categories-panel'),$filterButton: $s.find('.items-responsive-filter'),$categories: $s.find('.items-categories-container li')});$categories.each(function(catIndex) {var $category = $(this);initializeTestimonialStack($category, layout_customize);});});});}
function initializeTestimonialStack($category, layout_customize) {if ($category.data('testimonials-initialized')) {return;}
var $cards = $category.find('.testimonial-card');var $prevBtn = $category.find('.testimonials-stack-prev');var $nextBtn = $category.find('.testimonials-stack-next');var autoRotateInterval = null;var isAnimating = false;var isMouseHovering = false;var isEditableFocused = false;var rotationInterval = 10000;if ($cards.length === 0) return;var categoryId = $category.attr('data-categories-filter') || 'default-' + Math.random().toString(36).substr(2, 9);var visibilityEventName = 'visibilitychange.testimonials-' + categoryId;$category.data('testimonials-initialized', true);var allItems = [];$cards.each(function(index) {allItems.push({element: $(this),uniqueId: $(this).data('unique-id'),itemIndex: $(this).data('item-index')});});var currentIndex = 0;var totalItems = allItems.length;var cardCountClass = 'cards-' + Math.min(totalItems, 5);$category.find('.testimonials-stack-wrapper').addClass(cardCountClass);function rotateForward() {if (document.hidden) return;if (isAnimating || totalItems <= 1) return;isAnimating = true;$cards.addClass('animating');var maxPosition = totalItems - 1; // Highest position (e.g., 5 for 6 cards)
var movedCardId = null;$cards.each(function() {var $card = $(this);var currentPos = parseInt($card.attr('data-stack-position'));if (currentPos === maxPosition) {$card.attr('data-stack-position', 0);movedCardId = $card.data('unique-id');}});setTimeout(function() {if (document.hidden) {$cards.removeClass('animating');isAnimating = false;return;}
$cards.each(function() {var $card = $(this);var currentPos = parseInt($card.attr('data-stack-position'));var cardId = $card.data('unique-id');if (cardId !== movedCardId && currentPos !== maxPosition) {var newPos = currentPos + 1;$card.attr('data-stack-position', newPos);}});}, 200);currentIndex = (currentIndex - 1 + totalItems) % totalItems;setTimeout(function() {if (document.hidden) {$cards.removeClass('animating');isAnimating = false;return;}
$cards.removeClass('animating');isAnimating = false;}, 700);}
function rotateBackward() {if (document.hidden) return;if (isAnimating || totalItems <= 1) return;isAnimating = true;$cards.addClass('animating');var maxPosition = totalItems - 1; // Highest position (e.g., 5 for 6 cards)
var movedCardId = null;$cards.each(function() {var $card = $(this);var currentPos = parseInt($card.attr('data-stack-position'));if (currentPos === 0) {$card.attr('data-stack-position', maxPosition);movedCardId = $card.data('unique-id');}});setTimeout(function() {if (document.hidden) {$cards.removeClass('animating');isAnimating = false;return;}
$cards.each(function() {var $card = $(this);var currentPos = parseInt($card.attr('data-stack-position'));var cardId = $card.data('unique-id');if (cardId !== movedCardId && currentPos > 0) {var newPos = currentPos - 1;$card.attr('data-stack-position', newPos);}});}, 200);currentIndex = (currentIndex + 1) % totalItems;setTimeout(function() {if (document.hidden) {$cards.removeClass('animating');isAnimating = false;return;}
$cards.removeClass('animating');isAnimating = false;}, 700);}
function shouldPauseRotation() {return isMouseHovering || isEditableFocused;}
function updateRotationState() {if (shouldPauseRotation()) {stopAutoRotate();} else {startAutoRotate();}}
function startAutoRotate() {if (shouldPauseRotation()) {return;}
stopAutoRotate();if (totalItems > 1) {autoRotateInterval = setInterval(function() {rotateForward();}, rotationInterval); // 10 seconds
}}
function stopAutoRotate() {if (autoRotateInterval) {clearInterval(autoRotateInterval);autoRotateInterval = null;}}
function resetAutoRotate() {stopAutoRotate();startAutoRotate();}
$nextBtn.on('click', function(e) {e.preventDefault();rotateForward();resetAutoRotate();});$prevBtn.on('click', function(e) {e.preventDefault();rotateBackward();resetAutoRotate();});$cards.on('mouseenter', function() {isMouseHovering = true;updateRotationState();});$cards.on('mouseleave', function() {isMouseHovering = false;updateRotationState();});$category.on('focus', '[data-inline-edit-field]', function() {isEditableFocused = true;updateRotationState();});$category.on('blur', '[data-inline-edit-field]', function() {isEditableFocused = false;updateRotationState();});$category.find('.testimonial-favicon-link[data-rel="tooltip"]').each(function() {if (typeof $(this).tooltip === 'function') {$(this).tooltip();}});$(document).on('keydown', function(e) {if (!$category.is(':visible')) return;if ( isEditableFocused ) return;if (e.keyCode === 37) {rotateBackward();resetAutoRotate();} else if (e.keyCode === 39) {rotateForward();resetAutoRotate();}});startAutoRotate();$(document).off(visibilityEventName).on(visibilityEventName, function() {if (document.hidden) {stopAutoRotate();$cards.removeClass('animating');isAnimating = false;} else {if ($category.is(':visible')) {isAnimating = false; // Ensure flag is reset
updateRotationState();}}});$category.on('module_layout_categories.hide', function() {stopAutoRotate();$(document).off(visibilityEventName);$category.removeData('testimonials-initialized');});$category.on('module_layout_categories.show', function() {updateRotationState();});}
jQuery(function($) {GlobalCarouselModuleInitialize();});function GlobalCarouselModuleInitialize() {$( document ).on( "module_layout_categories.shown", function( event, categoryFilter ) {requestAnimationFrame(function() {var $visibleCarousels = $('.global-carousel-category[data-categories-filter="' + categoryFilter + '"] .s123-module-global-carousel-slider');$visibleCarousels.each(function() {var $carousel = $(this);var $section = $carousel.closest('.s123-module');var layout_customize = $section.find('.layout-customize').length > 0 ? tryParseJSON($section.find('.layout-customize').val()) : '';var intervalSetting = layout_customize && (layout_customize.carouselInterval || layout_customize.testimonialsInterval);var globalCarouselInterval = intervalSetting ? intervalSetting * 1000 : 10000;var carouselId = $carousel.attr('data-carousel-id') || 'unknown';if (!$carousel.data('carousel-initialized')) {initializeGlobalCarousel($carousel, globalCarouselInterval);} else {$carousel.data('currentIndex', 0);var $dots = $carousel.find('.s123-module-global-carousel-dot');$dots.removeClass('active').first().addClass('active');var $track = $carousel.find('.s123-module-global-carousel-track');if ($track.length > 0) {$track.css('transition', 'transform 0.5s ease');$track.css('transform', 'translateX(0px)');}}
bindCarouselArrowEvents($carousel);if (typeof S123 !== 'undefined' && S123.s123IconToSvg) {$(document).trigger('s123.page.ready.s123IconToSvg');}});setGlobalCarouselHeight();});});$(document).on('s123.page.ready', function( event ) {var $sections = $('.s123-module').has('.s123-module-global-carousel-slider');$sections.each(function() {var $s = $(this);if ($s.find('.items-categories-container li').length > 0) {var categories = new ModuleLayoutCategories({$items: $s.find('.global-carousel-category'),$categoriesContainer: $s.find('.s123-categories'),$filterButton: $s.find('.items-responsive-filter'),$categories: $s.find('.items-categories-container li')});}});var $carousels = $('.s123-module-global-carousel-slider').filter(function() {return $(this).closest('.global-carousel-category').is(':visible');});$carousels.each(function( index ) {var $carousel = $(this);var $section = $carousel.closest('.s123-module');var layout_customize = $section.find('.layout-customize').length > 0 ? tryParseJSON($section.find('.layout-customize').val()) : '';var globalCarouselInterval = 10000;if ( layout_customize != '' ) {var intervalSetting = layout_customize.carouselInterval || layout_customize.testimonialsInterval;if (intervalSetting) {globalCarouselInterval = intervalSetting * 1000;}}
initializeGlobalCarousel($carousel, globalCarouselInterval);bindCarouselArrowEvents($carousel);if (typeof S123 !== 'undefined' && S123.s123IconToSvg) {$(document).trigger('s123.page.ready.s123IconToSvg');}});});$( document ).on( "s123.page.load", function( event ) {setGlobalCarouselHeight();});if ( IsWizard() ) {$(document).on('wizard.preview.device.changed', function( event ) {setGlobalCarouselHeight();});}}
function bindCarouselArrowEvents($carousel) {var isRTL = $('html').attr('dir') === 'rtl';var carouselId = $carousel.attr('data-carousel-id') || 'default';$carousel.find('.s123-module-global-carousel-arrow-right, .s123-module-global-carousel-arrow-left, .s123-module-global-carousel-dot').off('click.globalCarousel' + carouselId);$carousel.find('.s123-module-global-carousel-arrow-right').on('click.globalCarousel' + carouselId, function(e) {e.preventDefault();e.stopPropagation();if (isRTL) {$carousel.trigger('globalCarousel.next');} else {$carousel.trigger('globalCarousel.next');}});$carousel.find('.s123-module-global-carousel-arrow-left').on('click.globalCarousel' + carouselId, function(e) {e.preventDefault();e.stopPropagation();if (isRTL) {$carousel.trigger('globalCarousel.prev');} else {$carousel.trigger('globalCarousel.prev');}});$carousel.find('.s123-module-global-carousel-dot').on('click.globalCarousel' + carouselId, function(e){e.preventDefault();e.stopPropagation();$carousel.trigger('globalCarousel.goTo', $(this).data('slide-to'));});}
function initializeGlobalCarousel($carousel, globalCarouselInterval) {var $track = $carousel.find('.s123-module-global-carousel-track');var $slides = $carousel.find('.s123-module-global-carousel-slide');var $dots = $carousel.find('.s123-module-global-carousel-dot');if ($carousel.data('carousel-initialized')) {return;}
$carousel.data('carousel-initialized', true);var originalSlides = parseInt($carousel.attr('data-original-slides')) || $slides.length;var totalSlides = $slides.length;$carousel.data('currentIndex', 0);$carousel.data('originalSlides', originalSlides);$carousel.data('totalSlides', totalSlides);var slideWidth = $slides.first().outerWidth();var slideGap = 20;var slideStep = slideWidth + slideGap;var originalItemsData = [];try {originalItemsData = JSON.parse($carousel.attr('data-original-items') || '[]');} catch(e) {console.error('Failed to parse original items data');}
$carousel.data('originalItemsData', originalItemsData);function addClonesAtEnd() {var originalSlides = $carousel.data('originalSlides');var $currentSlides = $track.find('.s123-module-global-carousel-slide');var currentCount = $currentSlides.length;for (var i = 0; i < originalSlides; i++) {var $originalSlide = $currentSlides.eq(i);var $clone = $originalSlide.clone(true);$clone.attr('data-slide-index', currentCount + i);$clone.attr('data-is-clone', 'true');$track.append($clone);}
$carousel.data('totalSlides', $track.find('.s123-module-global-carousel-slide').length);if (typeof lazyLoadInit === 'function') {lazyLoadInit();}}
function recalculateDimensions() {var $currentSlides = $track.find('.s123-module-global-carousel-slide');if ($currentSlides.length === 0) return;slideWidth = $currentSlides.first().outerWidth();slideStep = slideWidth + slideGap;var windowWidth = $(window).width();if (windowWidth >= 768 && windowWidth <= 1024) {slideGap = 18;slideStep = slideWidth + slideGap;} else if (windowWidth <= 767) {slideGap = 15;slideStep = slideWidth + slideGap;} else {slideGap = 20;slideStep = slideWidth + slideGap;}}
function updateSliderPosition(instant) {var isRTL = $('html').attr('dir') === 'rtl';var translateX;var currentIndex = $carousel.data('currentIndex') || 0;var originalSlides = $carousel.data('originalSlides');if (instant) {$track.addClass('no-transition');$track[0].offsetHeight;}
if (isRTL) {translateX = (currentIndex * slideStep);} else {translateX = -(currentIndex * slideStep);}
$track.css('transform', 'translateX(' + translateX + 'px)');if (instant) {requestAnimationFrame(function() {$track.removeClass('no-transition');});}
var mappedIndex = currentIndex % originalSlides;$dots.removeClass('active');if ($dots.length > 0) {$dots.eq(mappedIndex).addClass('active');}}
function nextSlide() {var currentIndex = $carousel.data('currentIndex') || 0;var originalSlides = $carousel.data('originalSlides');var totalSlides = $carousel.data('totalSlides');var shouldStartCloning = true;if (originalSlides > 10 && currentIndex < 5) {shouldStartCloning = false;}
var nextIndex = currentIndex + 1;if (shouldStartCloning && nextIndex > 0 && nextIndex % originalSlides === 0) {var nextSet = Math.floor(nextIndex / originalSlides);if (nextSet >= 2) {recalculateDimensions();$track.addClass('no-transition');$track.css('transition', 'none');$track[0].offsetHeight; // Force reflow
var $currentSlides = $track.find('.s123-module-global-carousel-slide');$currentSlides.slice(0, originalSlides).remove();currentIndex = currentIndex - originalSlides;nextIndex = nextIndex - originalSlides;$carousel.data('currentIndex', currentIndex);totalSlides = $track.find('.s123-module-global-carousel-slide').length;$carousel.data('totalSlides', totalSlides);$track.find('.s123-module-global-carousel-slide').each(function(idx) {$(this).attr('data-slide-index', idx);});var isRTL = $('html').attr('dir') === 'rtl';var translateX = isRTL ? (currentIndex * slideStep) : -(currentIndex * slideStep);$track.css('transform', 'translateX(' + translateX + 'px)');$track[0].offsetHeight;$track.removeClass('no-transition');$track.css('transition', '');}}
currentIndex = nextIndex;$carousel.data('currentIndex', currentIndex);totalSlides = $carousel.data('totalSlides');var needsClones = currentIndex >= totalSlides - (originalSlides * 2);if (shouldStartCloning && needsClones) {addClonesAtEnd();addClonesAtEnd();$carousel.data('totalSlides', $track.find('.s123-module-global-carousel-slide').length);}
updateSliderPosition(false);}
function prevSlide() {var currentIndex = $carousel.data('currentIndex') || 0;currentIndex = currentIndex - 1;if (currentIndex < 0) {currentIndex = 0;}
$carousel.data('currentIndex', currentIndex);updateSliderPosition(false);}
function goToSlide(index) {var originalSlides = $carousel.data('originalSlides');var currentIndex = $carousel.data('currentIndex') || 0;var currentSet = Math.floor(currentIndex / originalSlides);var targetIndex = (currentSet * originalSlides) + index;var totalSlides = $carousel.data('totalSlides');if (targetIndex >= 0 && targetIndex < totalSlides) {$carousel.data('currentIndex', targetIndex);updateSliderPosition(false);}}
var carouselId = $carousel.attr('data-carousel-id') || 'default';$carousel.off('globalCarousel.next.carousel' + carouselId + ' globalCarousel.prev.carousel' + carouselId + ' globalCarousel.goTo.carousel' + carouselId);var autoPlayInterval;var startAutoPlay, stopAutoPlay;if (globalCarouselInterval && globalCarouselInterval > 0) {if (typeof isMobileDevice !== 'undefined' && !isMobileDevice.any()) {startAutoPlay = function() {stopAutoPlay(); // Clear any existing interval
autoPlayInterval = setInterval(function() {nextSlide();}, globalCarouselInterval);};stopAutoPlay = function() {if (autoPlayInterval) {clearInterval(autoPlayInterval);autoPlayInterval = null;}};var carouselId = $carousel.attr('data-carousel-id') || $carousel.attr('data-total-slides') || Math.random().toString(36);$(document).off('visibilitychange.globalCarousel' + carouselId);$(window).off('blur.globalCarousel' + carouselId);$(window).off('focus.globalCarousel' + carouselId);$(window).on('blur.globalCarousel' + carouselId, function() {stopAutoPlay();});$(window).on('focus.globalCarousel' + carouselId, function() {$carousel.data('currentIndex', 0);requestAnimationFrame(function() {recalculateDimensions();updateSliderPosition(false);startAutoPlay();});});startAutoPlay();}}
$carousel.on('globalCarousel.next.carousel' + carouselId, function() {nextSlide();if (typeof startAutoPlay === 'function') {startAutoPlay();}});$carousel.on('globalCarousel.prev.carousel' + carouselId, function() {prevSlide();if (typeof startAutoPlay === 'function') {startAutoPlay();}});$carousel.on('globalCarousel.goTo.carousel' + carouselId, function(event, index) {goToSlide(index);if (typeof startAutoPlay === 'function') {startAutoPlay();}});$(window).off('resize.globalSlider' + carouselId).on('resize.globalSlider' + carouselId, function() {recalculateDimensions();updateSliderPosition(false);setGlobalCarouselHeight();});requestAnimationFrame(function() {recalculateDimensions();updateSliderPosition(false);setGlobalCarouselHeight();});}
function setGlobalCarouselHeight() {var $sections = $('.s123-module-global-carousel-slider').closest('.s123-module');$sections.each(function() {var $s = $(this);var $carousel = $s.find('.s123-module-global-carousel-slider');$carousel.find('.s123-module-global-carousel-slide, .box').css({ minHeight: '' });});}
function tryParseJSON(jsonString) {try {var o = JSON.parse(jsonString);if (o && typeof o === "object") {return o;}} catch (e) {return false;}
return false;}
jQuery(function($) {headersModuleInitialize_Layout();});function headersModuleInitialize_Layout() {$(document).on('s123.page.ready', function( event ) {var $sections = $('section.s123-module-headers:is(.layout-6,.layout-7,.layout-8,.layout-9,.layout-18,.layout-20,.layout-22,.layout-23,.layout-24,.layout-25,.layout-26,.layout-27,.layout-29,.layout-30,.layout-35,.layout-39,.layout-40,.layout-99,.layout-101,.mobile-layout-1,.mobile-layout-3,.mobile-layout-7,.mobile-layout-8,.mobile-layout-11');$sections.each(function( index ) {var $s = $(this);var $carousel = $s.find('[data-ride="carousel"]');var sliderSpeed = $s.data('slider-speed');if ( sliderSpeed == '' || parseInt(sliderSpeed) < 1 || parseInt(sliderSpeed) > 21 ) {sliderSpeed = 5000;} else {sliderSpeed = parseInt(sliderSpeed) * 1000;}
$s.find('.header1, .header2').each(function( index ) {var $this = $(this);if ( $this.data('line-height') !== undefined && $this.data('line-height') !== '' ) {var lineHeightVal = String($this.data('line-height'));if ( lineHeightVal === '1.15' || lineHeightVal === '1.25' || lineHeightVal === '1.35' ) {$this.get(0).style.setProperty('--header_line_height', lineHeightVal);$this.css('line-height', lineHeightVal);} else if ( lineHeightVal !== '0' ) {var computedLineHeight = 1.5 + (parseFloat(lineHeightVal) * 0.015);$this.get(0).style.setProperty('--header_line_height', computedLineHeight);$this.css('line-height', computedLineHeight);}}
if ( $this.data('letter-spacing') !== undefined && $this.data('letter-spacing') !== '' && String($this.data('letter-spacing')) !== '0' ) {var letterSpacingVal = parseFloat($this.data('letter-spacing')) * 0.01;$this.css('letter-spacing', letterSpacingVal + 'em');}
if ( $this.data('word-spacing') !== undefined && $this.data('word-spacing') !== '' && String($this.data('word-spacing')) !== '0' ) {var wordSpacingVal = parseFloat($this.data('word-spacing')) * 0.03;$this.css('word-spacing', wordSpacingVal + 'em');}});if( $s.hasClass('layout-20') ) {var $firstImage = $s.find('.headers-image').first();if ( $firstImage.length > 0 ) {if ( $firstImage.data('bg') !== undefined ) {var img = new Image();img.src = $firstImage.data('bg');img.onload = function() {var aspectRatio = this.width / this.height;$s.find('.headers-image').css('aspect-ratio',String(aspectRatio));if( $s.find('.headers-container').hasClass('circle-under-image') && aspectRatio < 1 ) {$s.addClass('corner-circle');}};} else {$firstImage.closest('.headers-img-wrap').addClass('circle-fixed-width');}}}
if( $s.hasClass('layout-22') || $s.hasClass('layout-29') || $s.hasClass('mobile-layout-7') ) {var $headersDescription = $s.find('.headers-description');var $headersimage = $s.find('.headers-image');if ( $headersimage.length == 0 ) {$headersimage = $s.find('.headers-bg-video');}
if ( $headersimage.length > 0 && $headersDescription.length > 0 ) {if ( ($headersDescription.get(0).offsetHeight - 60) > $headersimage.get(0).offsetHeight ) {$s.get(0).style.setProperty('--headers-description-height',$headersDescription.get(0).offsetHeight+'px');}}}
$carousel.carousel({interval: sliderSpeed});if( $s.hasClass('layout-26') && $s.attr('data-version') !== undefined && $s.attr('data-version') == '2' ) {if ( IsWizard() ) {$(document).on('site123.colorPicker.change',function( event ) {updateBackgroundColor();});}
updateBackgroundColor();}
function updateBackgroundColor() {var boxColorClass = $s.data('box-color');var color = $s.hasClass('bg-primary') ?getComputedStyle(document.documentElement).getPropertyValue('--modules_color_box') :getComputedStyle(document.documentElement).getPropertyValue('--modules_color_second_box');switch (boxColorClass) {case 'bg-primary-gray':color = '#ebedf0';break;case 'bg-primary-white':color = '#ffffff';break;case 'bg-primary-black':color = '#000000';break;case 'background-primary-color btn-primary-text-color':color = $s.hasClass('bg-primary') ?getComputedStyle(document.documentElement).getPropertyValue('--modules_color_section_main') :getComputedStyle(document.documentElement).getPropertyValue('--modules_color_second_section_main');break;}
$s.find('.headers-img-wrap').get(0).style.setProperty('--layout26OpacityColor',hexToRGB(color));}
function hexToRGB(hex) {var r = parseInt(hex.slice(1, 3), 16),g = parseInt(hex.slice(3, 5), 16),b = parseInt(hex.slice(5, 7), 16);return r + ", " + g + ", " + b;}
if( $s.data('image-width') == 2 ) {var sectionHeight = $s.height();$s.find('.headers-container').css('min-height',sectionHeight+'px');if( $s.hasClass('layout-22') ) {$s.find('.headers-image').css('min-height',sectionHeight+'px');}
$s.data('image-width',0);}});var $sections = $('section.s123-module-headers');$sections.each(function( index ) {var $s = $(this);$s.find('.custom-header-font').each(function( index ) {var $this = $(this);var customFont = $this.data('custom-font');if ( customFont.length > 0 ) {$this.css('font-family',customFont);}});$s.find('.header1, .header2').each(function( index ) {var $this = $(this);if( $s.hasClass('layout-7') || $s.hasClass('layout-9') || $s.hasClass('layout-22') || $s.hasClass('layout-23') || $s.hasClass('layout-24') || $s.hasClass('layout-26') || $s.hasClass('layout-27') || $s.hasClass('layout-29') || $s.hasClass('layout-33') || $s.hasClass('mobile-layout-1') || $s.hasClass('mobile-layout-7') ) {fitHeaderTextToParentContainer($this);}});$s.find('.h-s-form').each(function( index ) {let $this = $(this);hotelBookingWidgetInit($this);$this.off('submit').on('submit', function(event) {event.preventDefault();window.location.href = '/'+ $this.find('[data-id="page"] option').val() + '?' + $this.serialize();});});function fitHeaderTextToParentContainer( $textEl ) {if ( $textEl.length == 0 ) return;fontSize = parseFloat($textEl.css('font-size'));if ( !$.isNumeric(fontSize) ) return;var $parentContainer = $textEl.closest('.headers-text-resize-container');if ( $parentContainer.length > 0 && $parentContainer.width() < $textEl.width() ) {$textEl.css('visibility','hidden');var parentContainerWidth = $parentContainer.width();if ( $textEl.closest('section').hasClass('layout-9') || $textEl.closest('section').hasClass('layout-27') || $textEl.closest('section').hasClass('mobile-layout-1') ) {parentContainerWidth = parentContainerWidth + 5;}
if ( $textEl.closest('section').hasClass('layout-23') ) {parentContainerWidth = $parentContainer.innerWidth();}
var index = 0;while ( parentContainerWidth < $textEl.width() && index < 99 ) {index++;fontSize--;$textEl.get(0).style.setProperty('--header-font-size',fontSize);}
$textEl.css('visibility','unset');}}});S123_ActionButtons.init();});}
jQuery(function($) {HeadersModuleInitialize_Layout5();});function HeadersModuleInitialize_Layout5() {$(document).on('s123.page.ready', function( event ) {var $section = $('section.s123-module-headers.layout-5');$section.each(function( index ) {var $sectionThis = $(this);var $flickityContainer = $sectionThis.find('.carousel');var originalFirstImageSize = {};if ( $flickityContainer.length === 0 ) return;$flickityContainer.flickity({imagesLoaded: true,lazyLoad: 2,pageDots: false,wrapAround: true,percentPosition: false});});});}
jQuery(function($) {HeadersModuleInitialize_Layout30();});function HeadersModuleInitialize_Layout30() {$(document).on('s123.page.ready', function( event ) {var $section = $('section.s123-module-headers.layout-30, section.s123-module-headers.mobile-layout-11');$section.each(function( index ) {var $sectionThis = $(this);$sectionThis.find('.contactUsForm').each( function( index ) {var $form = $(this);var customFormMultiSteps = new CustomFormMultiSteps();customFormMultiSteps.init({$form: $form,$nextButton: $form.find('.next-form-btn'),$submitButton: $form.find('.submit-form-btn'),$previousButton: $form.find('.previous-form-btn'),totalSteps: $form.find('.custom-form-steps').data('total-steps')});var forms_GoogleRecaptcha = new Forms_GoogleRecaptcha();forms_GoogleRecaptcha.init($form);$form.validate({errorElement: 'div',errorClass: 'help-block',focusInvalid: true,ignore: ':hidden:not(.custom-form-step:visible input[name^="datePicker-"])',highlight: function (e) {$(e).closest('.form-group').removeClass('has-info').addClass('has-error');},success: function (e) {$(e).closest('.form-group').removeClass('has-error');$(e).remove();},errorPlacement: function (error, element) {if( element.is('input[type=checkbox]') || element.is('input[type=radio]') ) {var controls = element.closest('div[class*="col-"]');if( controls.find(':checkbox,:radio').length > 0 ) element.closest('.form-group').append(error);else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));}
else if( element.is('.select2') ) {error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));}
else if( element.is('.chosen-select') ) {error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));}
else {error.appendTo(element.closest('.form-group'));}},submitHandler: function( form ) {var $form = $(form);var clickAction = $form.data('click-action');$form.append($('<div class="conv-code-container"></div>'));var $convCodeContainer = $form.find('.conv-code-container');var thankYouMessage = translations.ThankYouAfterSubmmit;if ( $form.data('thanks-msg') ) {thankYouMessage = $form.data('thanks-msg');}
$form.find('button:submit').prop('disabled', true);S123.ButtonLoading.start($form.find('button:submit'));var url = "/versions/2/include/contactO.php";if ( $form.hasClass('custom-form') || $form.hasClass('horizontal-custom-form') ) {if ( !CustomForm_IsLastStep( $form ) ) {$form.find('.next-form-btn:visible').trigger('click');S123.ButtonLoading.stop($form.find('button:submit'));$form.find('button:submit').prop('disabled', false);return false;}
if ( !CustomForm_IsFillOutAtLeastOneField($form) ) {bootbox.alert(translations.fillOutAtLeastOneField);S123.ButtonLoading.stop($form.find('button:submit'));$form.find('button:submit').prop('disabled', false);return false;}
url = "/versions/2/include/customFormO.php";}
if ( forms_GoogleRecaptcha.isActive && !forms_GoogleRecaptcha.isGotToken ) {forms_GoogleRecaptcha.getToken();return false;}
$.ajax({type: "POST",url: url,data: $form.serialize(),success: function( data ) {var dataObj = jQuery.parseJSON(data);$form.trigger("reset");if ( clickAction == 'thankYouMessage' || clickAction == '' ) {bootbox.alert({title: translations.sent,message: thankYouMessage+'<iframe src="/versions/2/include/contactSentO.php?w='+$('#w').val()+'&websiteID='+dataObj.websiteID+'&moduleID='+dataObj.moduleID+'" style="width:100%;height:30px;" frameborder="0"></iframe>',className: 'contactUsConfirm',buttons: {ok: {label: translations.Ok}},backdrop: true});} else {if ( dataObj.conv_code.length > 0 ) {var $convCode = $('<div>' + dataObj.conv_code + '</div>');$convCodeContainer.html($convCode.text());}
if( top.$('#websitePreviewIframe').length ) {bootbox.alert({title: translations.previewExternalLinkTitle,message: translations.previewExternalLinkMsg.replace('{{externalLink}}','<b>'+dataObj.action.url+'</b>'),className: 'externalAlert'});} else {window.open(dataObj.action.url,'_self');}}
customFormMultiSteps.reset();forms_GoogleRecaptcha.reset();S123.ButtonLoading.stop($form.find('button:submit'));$form.find('button:submit').prop('disabled', false);WizardNotificationUpdate();}});return false;}});$form.find('.f-b-date-timePicker').each( function() {var $option = $(this);var $datePicker = $option.find('.fake-input.date-time-picker');var $hiddenInput = $option.find('[data-id="'+$datePicker.data('related-id')+'"]');var $datePickerIcon = $option.find('.f-b-date-timePicker-icon');var formBuilderCalendar = new calendar_handler();$datePicker.data('date-format',$form.data('date-format'));formBuilderCalendar.init({$fakeInput: $datePicker,$hiddenInput: $hiddenInput,$fakeInputIcon: $datePickerIcon,type: 'datePicker',title: translations.chooseDate,calendarSettings: {format: $datePicker.data('date-format'),weekStart: 0,todayBtn: "linked",clearBtn: false,language: languageCode,todayHighlight: true},onSubmit: function( selectedDate ) {$datePicker.html(selectedDate);$hiddenInput.val(selectedDate);}});});CustomForm_DisableTwoColumns($form);});});});}
